services:
  dextools-cron:
    container_name: dextools-cron
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # PostgreSQL
      - PGHOST=dextools-postgres
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGDATABASE=${POSTGRES_DB}
      - PGPORT=5432
      # MongoDB
      - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@dextools-mongodb:27017/${MONGO_DB}?authSource=admin
      # App
      - NODE_ENV=${NODE_ENV:-development}
      - TZ=Etc/UTC
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - dextools_network

networks:
  dextools_network:
    external: true
