services:
  dextools-listener:
    container_name: dextools-listener
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PGHOST=dextools-postgres
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGDATABASE=${POSTGRES_DB}
      - PGPORT=5432
      - NODE_ENV=production
      - TZ=Etc/UTC
      - CHAINWEB_HOST=https://kadena.dapp.runonflux.io
    networks:
      - dextools_network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  dextools_network:
    external: true
