const tokenIconsMap = {
  coin: "kadena.png",
  "kaddex.kdx": "kdx.png",
  "n_dd05101ff4df21179bfc038a912fc88c38d777a1.kdx": "kdx.png",
  "hypercent.prod-hype-coin": "hypercent.png",
  "runonflux.flux": "flux.png",
  "kdlaunch.token": "kdl.png",
  "free.babena": "babena.png",
  "free.anedak": "anedak.png",
  "mok.token": "mok.png",
  "lago.kwUSDC": "usdc.png",
  "kaddex.skdx": "skdx.png",
  "free.jodie-token": "jodie.png",
  "lago.kwBTC": "kwbtc.png",
  "free.kapybara-token": "kapy.png",
  "free.docu": "docushield.png",
  "free.kishu-ken": "kishuken.png",
  "kdlaunch.kdswap-token": "kdl.png",
  "arkade.token": "arkade.png",
  "free.KAYC": "kayc.png",
  "free.wiza": "wizz.png",
  "free.crankk01": "crankk.png",
  "free.corona-token": "corona.png",
  "free.maga": "maga-token.png",
  "free.finux": "finux.png",
  "free.ktoshi": "ktoshi.png",
  "n_b742b4e9c600892af545afb408326e82a6c0c6ed.zUSD": "usdc.png",
  "n_e309f0fa7cf3a13f93a8da5325cdad32790d2070.heron": "heron-token.png",
  "n_582fed11af00dc626812cd7890bb88e72067f28c.bro": "bro.png",
  "n_518dfea5f0d2abe95cbcd8956eb97f3238e274a9.AZUKI": "azuki_logo.png",
  "free.cyberfly_token": "cfly-logo.png",
  "n_ebe54249b2e9d68f5060961f3c419f8288d18dc2.unitt": "unitt.png",
};

const tickersIconsMap = {
  kda: "kadena.png",
  coin: "kadena.png",
  kdx: "kdx.png",
  hype: "hypercent.png",
  flux: "flux.png",
  kdl: "kdl.png",
  babe: "babena.png",
  babena: "babena.png",
  anedak: "anedak.png",
  mok: "mok.png",
  USDC: "usdc.png",
  skdx: "skdx.png",
  jodie: "jodie.png",
  kwBTC: "kwbtc.png",
  kapy: "kapy.png",
  docu: "docushield.png",
  kishk: "kishuken.png",
  arkd: "arkade.png",
  kayc: "kayc.png",
  wiza: "wizz.png",
  crakk: "crankk.png",
  crna: "corona.png",
  maga: "maga-token.png",
  finux: "finux.png",
  zUSD: "usdc.png",
  heron: "heron-token.png",
  bro: "bro.png",
  AZUKI: "azuki_logo.png",
  cfly: "cfly-logo.png",
  unitt: "unitt.png",
  kto: "ktoshi.png",
};

function extractTokenName(tokenContract) {
  if (tokenContract.includes(".")) {
    return tokenContract.split(".").pop();
  }
  return tokenContract;
}

module.exports = { tickersIconsMap, tokenIconsMap, extractTokenName };
