services:
  api:
    container_name: dextools-api
    build: .
    ports:
      - "0.0.0.0:${PORT}:${PORT}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - TZ=Etc/UTC

      - PGHOST=dextools-postgres
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_SSL=${POSTGRES_SSL}

      - MONGO_HOST=dextools-mongodb
      - MONGO_DB=${MONGO_DB}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}

      - CHAINWEB_DB_HOST=${CHAINWEB_DB_HOST}
      - CHAINWEB_DB_NAME=${CHAINWEB_DB_NAME}
      - CHAINWEB_DB_USER=${CHAINWEB_DB_USER}
      - CHAINWEB_DB_PASSWORD=${CHAINWEB_DB_PASSWORD}

    env_file: .env
    networks:
      - dextools_network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:${PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  dextools_network:
    external: true
